import { createHash } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'yaml';
import { globsToGrepFile } from './glob.utils.js';
import {
  CHARS_PER_TOKEN,
  DEFAULT_CONTEXT_BUDGET_TOKENS,
  EVENT_HOOK_TIMEOUT_SECONDS,
  HOOK_TIMEOUT_SECONDS,
} from './profile.constants.js';
import { ContextBudgetExceededError, InvalidProfileError } from './profile.errors.js';
import type {
  CompiledProfile,
  CompileInput,
  HookMatcherEntry,
  ProfileLayer,
} from './types/profile.types.js';

// Paths interpolated into generated shell (single-quoted). A path containing a
// single quote or newline could break out of the quoting, so we reject those
// rather than trust the caller — these are enforcement scripts.
const SHELL_UNSAFE_PATH = /['"\n`$\\]/;

export function parseProfileLayer(yamlText: string): ProfileLayer {
  const raw = parse(yamlText) as Record<string, unknown> | null;
  if (!raw || typeof raw !== 'object' || typeof raw.name !== 'string' || !raw.name) {
    throw new InvalidProfileError('A profile layer needs at least a non-empty `name`.');
  }
  for (const key of ['skills', 'subagents', 'mcp'] as const) {
    if (raw[key] !== undefined && !Array.isArray(raw[key])) {
      throw new InvalidProfileError(`Profile field \`${key}\` must be a list.`);
    }
  }
  return raw as unknown as ProfileLayer;
}

function estimateTokens(text: string): number {
  return Math.ceil(text.length / CHARS_PER_TOKEN);
}

function validateInput(input: CompileInput): void {
  const scopeIn = input.task.scopeIn.filter((g) => g.trim());
  if (scopeIn.length === 0) {
    throw new InvalidProfileError(
      'Task scope-in is empty; a session with no scope can edit nothing.',
    );
  }
  for (const [label, path] of [
    ['worktreePath', input.worktreePath],
    ['eventsFile', input.eventsFile],
    ['outDir', input.outDir],
  ] as const) {
    if (SHELL_UNSAFE_PATH.test(path)) {
      throw new InvalidProfileError(
        `${label} contains characters unsafe for a generated hook: ${path}`,
      );
    }
  }
}

function mergeLayers(base: ProfileLayer, role?: ProfileLayer): ProfileLayer {
  if (!role) return base;
  return {
    name: role.name,
    conventions: [base.conventions, role.conventions].filter(Boolean).join('\n\n'),
    skills: [...new Set([...(base.skills ?? []), ...(role.skills ?? [])])],
    subagents: [...new Set([...(base.subagents ?? []), ...(role.subagents ?? [])])],
    hooks: { ...base.hooks, ...role.hooks },
    mcp: [...new Set([...(base.mcp ?? []), ...(role.mcp ?? [])])],
    contextBudget: role.contextBudget ?? base.contextBudget,
  };
}

function buildContextMarkdown(merged: ProfileLayer, input: CompileInput): string {
  const { task, sessionId } = input;
  const scopeOut = task.scopeOut?.length ? task.scopeOut.join(', ') : 'none declared';
  const sections = [
    `# Pupitre session ${sessionId} — task ${task.id}`,
    `## Goal\n${task.goal}`,
    `## Scope\n- In: ${task.scopeIn.join(', ')}\n- Out: ${scopeOut}\n` +
      'Editing outside scope-in is blocked by a hook and re-checked at the merge gate.',
    `## Acceptance criteria\n${task.acceptance.map((a) => `- ${a}`).join('\n')}`,
    merged.conventions ? `## Conventions\n${merged.conventions}` : undefined,
    task.knowledgeSlice ? `## Codebase knowledge\n${task.knowledgeSlice}` : undefined,
    '## Session protocol\n' +
      '- Work only inside this worktree, on the current branch. Never touch `.claude/`.\n' +
      '- When every acceptance criterion is met and all work is committed, run exactly:\n' +
      '  `pup session done "<one-line summary>"`\n' +
      '  (if `pup` is not found, run `node "$PUP_BIN" session done "<one-line summary>"`).\n' +
      '- If you are blocked on something only a human can decide, say so and stop.',
  ];
  return sections.filter(Boolean).join('\n\n');
}

/**
 * Scope enforcement. Task-controlled patterns live in sidecar files read via
 * `grep -E -f`, so no glob value is ever interpolated into shell source; only
 * Pupitre-owned, validated paths are. REL is normalized and parent traversal
 * is denied before matching.
 */
function buildScopeHookScript(input: CompileInput): string {
  const hooksDir = join(input.outDir, 'hooks');
  return `#!/bin/sh
# PreToolUse(Edit|Write) scope enforcement — generated by the Pupitre profile compiler.
INPUT=$(cat)
# Fail closed: if jq is missing or the payload can't be parsed, block rather than allow.
FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty') || {
  echo "BLOCKED: scope hook could not parse tool input." >&2; exit 2; }
[ -z "$FILE" ] && { echo "BLOCKED: no file_path in tool input." >&2; exit 2; }
WORKTREE='${input.worktreePath}'
case "$FILE" in
  "$WORKTREE"/*) REL=\${FILE#"$WORKTREE"/} ;;
  *) echo "BLOCKED: file is outside the session worktree." >&2; exit 2 ;;
esac
# Normalize: collapse // once (idempotent), then strip ./ and /./ segments to a
# fixpoint so repeated prefixes like ././ can't slip past the .claude/ and scope
# checks. The slash-collapse stays OUT of the loop — it always "matches" a slash,
# which would make ta branch forever; only the length-reducing strips loop.
REL=$(printf '%s' "$REL" | sed -e 's#//*#/#g' -e ':a' -e 's#/\\./#/#g; s#^\\./##' -e 'ta')
case "/$REL/" in *"/../"*) echo "BLOCKED: path traversal is not allowed." >&2; exit 2 ;; esac
if printf '%s\\n' "$REL" | grep -qiE '^\\.claude/'; then
  echo "BLOCKED: .claude/ is owned by Pupitre and read-only for sessions." >&2; exit 2
fi
if printf '%s\\n' "$REL" | grep -qE -f '${join(hooksDir, 'scope-out.pat')}'; then
  echo "BLOCKED: file is in scope-out for this task." >&2; exit 2
fi
if printf '%s\\n' "$REL" | grep -qE -f '${join(hooksDir, 'scope-in.pat')}'; then exit 0; fi
echo "BLOCKED: file is outside this task's scope-in." >&2
exit 2
`;
}

function buildBashGuardScript(): string {
  return `#!/bin/sh
# PreToolUse(Bash) guard — generated by the Pupitre profile compiler.
# Best-effort (decision 6): blocks obvious writes into .claude/; the merge gate
# (diff-vs-scope + drift hash) is the authoritative backstop.
INPUT=$(cat)
CMD=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty')
[ -z "$CMD" ] && exit 0
if printf '%s' "$CMD" | grep -qiE '(>>?|\\btee\\b|\\bsed\\b[^|]*-i|\\bperl\\b[^|]*-i|\\brm\\b|\\bmv\\b|\\bcp\\b|git +apply|git +checkout)[^|]*\\.claude/'; then
  echo "BLOCKED: shell writes into .claude/ are not allowed; it is owned by Pupitre." >&2
  exit 2
fi
exit 0
`;
}

function buildEventHookScript(input: CompileInput): string {
  return `#!/bin/sh
# Event hook — generated by the Pupitre profile compiler. Appends every hook
# payload as one JSONL line tagged with the session id.
jq -c --arg sid "\${PUP_SESSION_ID:-unknown}" '. + {pup_session_id: $sid}' >> '${input.eventsFile}'
`;
}

export function compileProfile(input: CompileInput): CompiledProfile {
  validateInput(input);
  const merged = mergeLayers(input.base, input.role);
  const contextMarkdown = buildContextMarkdown(merged, input);
  const contextBudget = merged.contextBudget ?? DEFAULT_CONTEXT_BUDGET_TOKENS;
  const tokenEstimate = estimateTokens(contextMarkdown);
  if (tokenEstimate > contextBudget) {
    throw new ContextBudgetExceededError(tokenEstimate, contextBudget);
  }

  const hookPath = (name: string) => join(input.outDir, 'hooks', name);
  const eventEntry: HookMatcherEntry[] = [
    {
      hooks: [
        { type: 'command', command: hookPath('event-log.sh'), timeout: EVENT_HOOK_TIMEOUT_SECONDS },
      ],
    },
  ];
  const securityPreToolUse: HookMatcherEntry[] = [
    {
      matcher: 'Edit|Write',
      hooks: [
        { type: 'command', command: hookPath('scope-enforce.sh'), timeout: HOOK_TIMEOUT_SECONDS },
      ],
    },
    {
      matcher: 'Bash',
      hooks: [
        { type: 'command', command: hookPath('bash-guard.sh'), timeout: HOOK_TIMEOUT_SECONDS },
      ],
    },
  ];

  // Additive-only invariant (docs/03-profiles.md): layer-supplied hooks are
  // appended after the compiler's security/event hooks, never allowed to replace
  // them. Spread the layer's map first, then overwrite the guarded events with
  // guard-first concatenations.
  const layerHooks = merged.hooks ?? {};
  const settings = {
    hooks: {
      ...layerHooks,
      PreToolUse: [...securityPreToolUse, ...(layerHooks.PreToolUse ?? [])],
      PostToolUse: [...eventEntry, ...(layerHooks.PostToolUse ?? [])],
      Stop: [...eventEntry, ...(layerHooks.Stop ?? [])],
      Notification: [...eventEntry, ...(layerHooks.Notification ?? [])],
    },
  };

  const scopeIn = input.task.scopeIn.filter((g) => g.trim());
  const scopeOut = (input.task.scopeOut ?? []).filter((g) => g.trim());
  const files: Record<string, string> = {
    'context.md': contextMarkdown,
    'settings.json': `${JSON.stringify(settings, null, 2)}\n`,
    'hooks/scope-enforce.sh': buildScopeHookScript(input),
    'hooks/bash-guard.sh': buildBashGuardScript(),
    'hooks/event-log.sh': buildEventHookScript(input),
    'hooks/scope-in.pat': globsToGrepFile(scopeIn),
    'hooks/scope-out.pat': scopeOut.length ? globsToGrepFile(scopeOut) : '',
  };

  const hash = createHash('sha256')
    .update(JSON.stringify({ files, userConfigHash: input.userConfigHash }))
    .digest('hex');

  return { hash, tokenEstimate, contextBudget, contextMarkdown, settings, files };
}

export function writeCompiledProfile(compiled: CompiledProfile, outDir: string): void {
  for (const [rel, content] of Object.entries(compiled.files)) {
    const target = join(outDir, rel);
    mkdirSync(join(target, '..'), { recursive: true });
    writeFileSync(target, content);
    if (rel.endsWith('.sh')) chmodSync(target, 0o755);
  }
  writeFileSync(join(outDir, 'profile-hash'), `${compiled.hash}\n`);
}

/**
 * Hash the parts of the user's ~/.claude that shape session behavior (decision 9:
 * sessions inherit user config; drift is detected via this snapshot hash).
 */
export function snapshotUserConfigHash(claudeDir: string): string {
  const hash = createHash('sha256');
  for (const rel of ['settings.json', 'CLAUDE.md']) {
    const path = join(claudeDir, rel);
    hash.update(rel);
    hash.update(existsSync(path) ? readFileSync(path, 'utf8') : '<absent>');
  }
  return hash.digest('hex');
}
